### ISSUE TITLE
直接提供docker应用会不会更好

### ISSUE THREAD

**Issue by xyy94813** [Lobos/qenya#1]
感觉这个如果能直接提供 docker 应用，感觉会方便很多啊。

如果能够根据 graphql 的 schema 文件自动 mock 数据那就更棒了

**Comment by Lobos** [comment]
对使用者来说docker的门槛还是有点高吧。
现在是可以根据schema mock数据的啊。

**Comment by xyy94813** [comment]
个人认为， 使用 docker 镜像，少了很多环境，对于使用者来说应该是降低难度了吧。docker 的 GUI 工具很方便啊，不过对于开发者倒是又提升了点难度。
